name: Versioning

on:
  pull_request:
    types: [ labeled ]

jobs:
  bump-patch-version:
    if: ${{ github.event.label.name == 'patch' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: git config user.name $GITHUB_ACTOR
      - run: git config user.email gh-actions-${GITHUB_ACTOR}@github.com
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: npm version patch
      - run: git push origin main --tags
      - uses: actions/upload-artifact@v2
        with:
          name: src
          path: ./

  bump-minor-version:
    if: ${{ github.event.label.name == 'minor' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: git config user.name $GITHUB_ACTOR
      - run: git config user.email gh-actions-${GITHUB_ACTOR}@github.com
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: npm version minor
      - run: git push origin main --tags
      - uses: actions/upload-artifact@v2
        with:
          name: src
          path: ./

  bump-major-version:
    if: ${{ github.event.label.name == 'major' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: git config user.name $GITHUB_ACTOR
      - run: git config user.email gh-actions-${GITHUB_ACTOR}@github.com
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: npm version major
      - run: git push origin main --tags
      - uses: actions/upload-artifact@v2
        with:
          name: src
          path: ./